server:
  port: 9098

management:
  security:
    enabled: false
  trace:
    include: request_headers,response_headers,cookies,authorization_header,errors,path_info,path_translated,context_path,user_principal,parameters,query_string,auth_type,remote_address,session_id,remote_user


security:
  sessions: stateless
  user:
    password: none

logging:
  level:
    org.springframework.security: DEBUG